oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
custom_core:
    resource: "@CustomCoreBundle/Resources/config/routing.yml"
    prefix:   /core 
