#oc_platform_homepage:
#    path:     /
#    defaults: { _controller: OCPlatformBundle:Default:index }
oc_platform_homepage:
    path:     /hello_world
    defaults: { _controller: OCPlatformBundle:Advert:index }
